# These are supported funding model platforms

github: pmusolino
patreon: evanyou
open_collective: # Replace with open_collective
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with tidelift
custom: https://www.paypal.me/pmusolino

